name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t basavaraj684/frontend  .

      - name: Publish Image to docker hub
        run: docker push basavaraj684/frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull basavaraj684/frontend:latest
      - name: Delete old container
        run: docker rm -f ecom-frontend-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name ecom-frontend-container  basavaraj684/frontend
